version: '3'

services:
  db:
    image: mariadb:10.6
    env_file: ../docker/.env.db
    ports:
      - "3306:3306"
    volumes:
      - ../data/mariadb:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    env_file: ../docker/.env.keycloak
    command:
      - start-dev
    ports:
      - "8080:8080"
    volumes:
      - ../data/keycloak:/opt/keycloak/data

  web:
    build:
      context: ../web
      dockerfile: Dockerfile    
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: ../docker/.env.web
    depends_on:
      - db
      - keycloak
    ports:
      - "3011:3000"
    volumes:
      - ../web:/app

volumes:
  mariadb_data:
  keycloak_data:
