services:
  postgres_db:
    hostname: postgres_db
    container_name: postgres_db
    image: postgres:15.6
    volumes:
      - ../data/postgres/data/:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - '5433:5432'

  keycloak_web:
    hostname: keycloak_web
    container_name: keycloak_web
    image: quay.io/keycloak/keycloak:25.0.1    
    env_file: .env
    command:
      - start-dev
      #- --log-level=DEBUG,org.keycloak.authentication:TRACE
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
