services:
  db:
    hostname: db
    container_name: db
    image: mariadb:10.6
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ../data/mariadb:/var/lib/mysql

  web:
    hostname: web
    container_name: web
    build:
      context: ../web
      dockerfile: Dockerfile    
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    depends_on:
      - db
    ports:
      - "3011:3000"
    volumes:
      - ../web:/app
